defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: sto3psl/dw-ci:1.1.0

cache: &cache
    key: v3-dependency-cache-{{ checksum "package-lock.json" }}

version: 2
jobs:
    install:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  key: v1-install-cache-{{ checksum "package-lock.json" }}

            - run: npm ci

            - save_cache:
                  <<: *cache
                  paths:
                      - node_modules
                      - ~/.npm

            - save_cache:
                  key: v1-install-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/.npm
    test:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  <<: *cache

            - run:
                  command: |
                      mkdir -p ~/reports/ava
                      npm test -- --tap | npx tap-xunit > ~/reports/ava/results.xml
            - store_test_results:
                  path: ~/reports
            - store_artifacts:
                  path: ~/reports

    lint:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  <<: *cache

            - run: npm run lint

workflows:
    version: 2
    install, test and lint:
        jobs:
            - install:
                  filters:
                      tags:
                          only: /^v.*/

            - test:
                  filters:
                      tags:
                          only: /^v.*/
                  requires:
                      - install

            - lint:
                  filters:
                      tags:
                          only: /^v.*/
                  requires:
                      - install
